---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-10.04
    driver_config:
      customize:
        memory: 2048
        cpus: 2

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[ps2dev::default]
    attributes:
